### ISSUE TITLE
Is it possible to check results by recording raw sequences?

### ISSUE THREAD

**Issue by zealseeker** [jamigo/tagFinder#1]
Hi
It's a very nice tool for DEL research.

I am using in house scripts to count the reads that match a particular compound. However, when comparing the results from tagFinder, I found that it detected more than my scripts did. However, I cannot make sure who is wrong.
So I'd like to check it by getting the raw sequences corresponding to a particular compound. I'm not good at perl. So can you add some example codes or add this feature to tagFinder? I think it will also be useful for trouble shooting of NGS related techniques.

For example,
a sequence AATTCCGG occurs 10 times detected by my script and 11 times by tagFinder. I'd like to check whether the additional one is correct (only one bp in difference).

By the way, have the authors considered that one bp error may similar with two tag sequence?
For example
```
Tag1   AATTCCGG
Tag2   AATCGCGG
Query  AATTGCGG
```
The query sequence `AATTGCGG` is similar both to tag1 and tag2. So I think it should be removed.

**Comment by jamigo** [comment]
this issue needs further discussion.

1. tagFinder is able to detect tags not looking to the entire headpiece or closing sequence but to a anchor (7bp by default) in those boundary sequences. other algorithms that look for those exact sequences will miss potential well coded compounds.

2. the 1bp error in the coding tag sequence is only intended for tags that are 2bp or more apart. if you're using tags that are only 1bp apart you are not able to uniquely identify a tag using the 1bp error allowed option.

having said that, I'm not planning to dig deeper into error handling, since any other effort implies too many assumptions that drastically reduce the fidelity of the results. if you're using a set of tags with distance 1 among all them, then I would recommend not to use the 1bp error allowed option, and run tagFinder with the default perfect match expected mode, which should match your in-house results.

**Comment by zealseeker** [comment]
@jamigo 
Thank you very much for the detailed reply.
It's true that 2bp or more apart tags are preferred in tag sequence design. Since the results are similar and consistent, I won't take efforts to check why they are not exactly the same.

**Comment by jamigo** [comment]
yes, this is not a tagFinder issue, but don't get me wrong. checking why your results are not the same as the ones you get with an external tool is always beneficial, not only to improve your code but to get a better understanding of your data. you have already found why your results may not be consistent (you're working with distance 1 tags and you're trying to make assumptions on ambiguous tags), therefore you can continue working with your code and data with higher confidence on your results. thank you anyway for the discussion.
